OFFICIAL_BACKEND_BASE_URL=https://api.prothesis.ru/
COMMUNITY_BACKEND_BASE_URL=https://community.invalid/
LOCAL_BACKEND_BASE_URL=http://127.0.0.1:8000/

PROJECT_LANDING_URL=https://prothesis.ru/
PROSTHESIS_GUIDE_URL=https://drive.google.com/file/d/1TqZTdqmVpPDhjSL2WnfT9wohUkeKcAlp/view?usp=sharing
APP_GUIDE_URL=https://drive.google.com/file/d/1A2usxykovqEe099k2ItJ9acGboUhyZ13/view?usp=sharing
BACKEND_GUIDE_URL=https://drive.google.com/file/d/1RrIl7wzfEjwOqdwEEhMq3LTtUpla6rIw/view?usp=sharing
APP_REPOSITORY_URL=https://github.com/graevsky/6thFinger-App
ESP32_FIRMWARE_URL=https://github.com/graevsky/6thFinger-Controller
BACKEND_REPOSITORY_URL=https://github.com/graevsky/6thFinger-Backend

EMAIL_OFF=true
