BACKEND_BASE_URL=https://api.prothesis.ru/

APP_GUIDE_URL=https://docs.google.com/document/d/1MEejkdQEGTkvxDuX7fgXnzfzSTgcVONKTlj-WCBkAp0/edit?usp=sharing
APP_REPOSITORY_URL=https://github.com/graevsky/6thFinger-App
ESP32_FIRMWARE_URL=https://github.com/graevsky/6thFinger-Controller
BACKEND_REPOSITORY_URL=https://github.com/graevsky/6thFinger-Backend

EMAIL_OFF=false
